### ISSUE TITLE
Question about readme

### ISSUE THREAD

**Issue by felixsanz** [jaawerth/nrun.vim#5]
Hi there! Thanks for the plugin, works wonderful :)

But in your readme you said:

> For more on Neomake config, see their docs - I like to combine the above with:
> `autocmd! FileType javascript,BufWinEnter,BufWritePost * Neomake`

If i use this autocmd i get an error. What you really meant to say?

**Comment by jaawerth** [comment]
@felixsanz 

Apologies for the slow response! And for that being in the docs - not sure how that ended up getting pasted, as it was a result of me tinkering with getting it to trigger for anything with filetype javascript regardless of extension, but I pretty much just go by extension. Really I should just reference the Neomake docs on this, but Neomake uses the example
```
autocmd! BufWritePost * Neomake
```
which will launch Nemake regardless of file type/extension.

My own `init.vim` is a little more involved and I have stuff split into a bunch of `augroups, and I don't launch Neomake for every file type. I use
```vimscript
au FileType javascript,BufWinEnter,BufWritePost *.js,*.jsx Neomake
```

Anyway, thanks for pointing this out - I'll update it this weekend!
